import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next js Two Factor Authentication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={recursive.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
